### ISSUE TITLE
Data delivery to settlement reports (Calculation results)

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#1023]
### Synopsis 
As a grid access provider
I want to peek and dequeue net exchange per grid area
so that I can verify that Datahub has calculated correctly

### Acceptance criteria
- [ ] Enable settlement reports to get calculations results.

### Tasks
- [x] Add warehouse in tf + app settings @BjarkeMeier 
See https://registry.terraform.io/providers/databricks/databricks/latest/docs/resources/sql_endpoint
- [x] Implement GetSettlementReportResultAsync for grid area provider @JesperGomes 
- [x] Implement GetSettlementReportResultAsync for energy supplier @JesperGomes 
- [x] Static factory method for creating DatabricksSqlResponse objects
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0
https://learn.microsoft.com/en-us/aspnet/core/fundamentals/http-requests?view=aspnetcore-7.0#typed-clients
- [x] Contract test to ensure table column names in .NET/Python are in sync? @BjarkeMeier 
- [x] Contract test to ensure enum values in .NET/Python are in sync? @BjarkeMeier 
- [x] Cleanup SqlStatementClient (make it a general client  without application specific stuff) @JesperGomes 
- [ ] Only include latest batch/result in cases of "duplicate" rows
