### ISSUE TITLE
Integration test Settlement Report query with a real Databricks workspace

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/opengeh-wholesale#1212]
NOTE: VOLT AND OUTLAWS MIGHT WANT TO BE PART OF THIS WORK

### Synopsis
_____________
As a developer 
I want my Settlement Report code to be integration tested with a real Databricks workspace in the CI
so that I catch potential bugs before they end up in main

### Acceptance Criteria
________________
- [x] Sql queries for settlement reports are tested against Databricks SQL API
- [x] The tests are executred in the CI

### Task List
_________________
- [x] Add a serverless warehouse to the integration test databricks workspace ('databricks-playground'). According to Outlaws the integration test resource group has no firewall issues.
- [x] Make basic integration test of SqlStatementClient @JesperGomes
- [x] Integration test of SettlementReportResultQueries
