### ISSUE TITLE
Rename obsolete "batch" and "process type" terms

### ISSUE THREAD

**Issue by johevemi** [Energinet-DataHub/opengeh-wholesale#1280]
# Synopsis

For refinement: What about positive/negative grid loss vs grid loss/system correction (and residual)?

# Acceptance Criteria

- [ ] No occurrences of the terms "batch" or "process type" exists in the GitHub repo `opengeh-wholesale`
- [ ] "batch" is replaced with "calculation"
- [ ] "process type" is replaced with "calculation type"

# Tasks

Rename "batch" to "calculation" in:

- [x] frontend
- [x] "Batch*" project names [PR: https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1843]
  - [x] Folders, projects, solution
  - [x] ci-dotnet.yml
  - [x] AssemblyName, RootNamespace
  - [x] Namespaces
- [x] dotnet
  - [x] Contracts (NuGet package), release-notes, documentation [PR: https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1849]
  - [x] Database migrations [PR: https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1851]
  - [x] Web API, swagger, tests, external dependencies 
    - [x] Wholesale 
      - [x] [PR: https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1858]
      - [x] [PR: https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1866]
    - [x] BFF [PR: https://github.com/Energinet-DataHub/greenforce-frontend/pull/2489]

- [x] EXISTING_BATCH_ID => I suggest we completely remove this dependency, it is possible by using search instead of get
    - [x] CD [PR: https://github.com/Energinet-DataHub/dh3-environments/pull/863]
    - [x] dh3-secrets [PR: https://github.com/Energinet-DataHub/dh3-dev-secrets/pull/24]
- [x] C4 model
  - [x] In wholesale [PR: https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1846]
- [x] Update dictionary in Confluence
- [x] python - batch [PR: https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1872]
- [x] python - process-type [PR: https://github.com/Energinet-DataHub/opengeh-wholesale/pull/1874]
  - [x] parameter to job
  - [x] File "process-type.json" used for contract testing between python and dotnet

- [x] python - process type - the following was not renamed as it impacts the data schema
<img width="377" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUk1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--164d439a64f01a15a5ecbd01cb3d906ee0956022/image.png" alt="image.png" />

- [x] python - batch - the following was not renamed as it impacts the data schema
<img width="449" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWs0QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--434888068b4b28577bcb8431073d8961131f2b07/image.png" alt="image.png" />

- [ ] ~python+dotnet: If we want to save into delta table, then it would be a waste of time to refactor the files shown below:~
<img width="1079" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMTRkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c377254fb4ecee61f77776094fc325f5d62d1a92/image.png" alt="image.png" />
<img width="1298" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkVkQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56b35a27069f019ca07b5721744d4b006fe36bee/image.png" alt="image.png" />

**Comment by PerLysemose** [comment]
Vi aftalte d. 3/8 at udviklerne sammen finder en tilgang til at løse denne story. Dette gøres først når Jonas er tilbage fra ferie. Indtil da er den blokeret.

**Comment by MadsBloendAndersen** [comment]
@MadsBloendAndersen will arrange a meeting where we will discuss this, with team.
