### ISSUE TITLE
[BUG] Service bus messages not always sent (or very much delayed)

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/opengeh-wholesale#1314]
**Observation**
Our domain test is often failing because no messages appears on the service bus within 15 minutes after the calculation is done.  It turns out that messages are often delayed for a significant amount of time (sometimes a day). Maybe they are sometimes only sent after re-deploy?

**Environment**
U001

**Expected result**
Service bus messages should start appearing within 15 minutes after calculation has finalized

**Actual result**
Sometimes messages are not appearing on the service bus - or at least they are very much delayed.

## Tasks

Consider
- [ ] Is it ok that we cannot scale out wholesale API?
- [x] Does wholesale API need to be "always on"?
- [ ] How can we enable loglevel `debug|trace` in production?
- [ ] How can we share logging concepts and functionality across product teams?
- [x] Give developers List and Get permissions to wholesale internal keyvault secrets in u-001 (and more?)?

### Done Tasks
- [x] Use logging scopes to be able to effectively filter hosted services in Application Insights
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/5d575641-fd75-4557-9041-ffe4359aae2f)
- [x] Configure app service to log information in Application Insights @BjarkeMeier 
```
Logging__ApplicationInsights__LogLevel__Default: Information
Logging__ApplicationInsights__LogLevel__Microsoft: Warning
```
- [x] Fix problem 
- [x] Check hosted services in health checks @BjarkeMeier 
UPDATE: Done for OutboxSenderTrigger but not the other services due to code duplication problems (see next task)
- [x] Move RepeatedTrigger, IHostedServiceReadinessMonitor, and HostedServiceReadinessMonitor to geh-core and replace the current implementations from wholesale
