### ISSUE TITLE
[DRAFT] Missing data in Wholesale calculations 

### ISSUE THREAD

**Issue by energinet-ajw** [Energinet-DataHub/opengeh-wholesale#1531]
As an EDI developer
I want time series points to be included in the result even if it is missing the charge price
so that I can easily set it to 'incomplete' in the message to the actors

# Acceptance criteria
- [ ] Price is set to NULL in the wholesale_results table if prices are missing.
- [ ] Price in Service bus message is set to NULL for the missing price

# Tasks
- [ ] TODO Fix nullable issues in wholesale output delta table: **price/quantity/amount** should be nullable.
- [ ] Python tests: have we covered edges cases when price or time series is missing (NULL) 
# Note
BRS-27. should contain more information on the matter.

- The charge price cannot be null in input schema (constraint).
- Charge price points can be missing.
- The time serie points (energy) can be missing.
- If data is missing EDI handles the response to the actor (incomplete).
