### ISSUE TITLE
Remove not needed controller endpoints from SettlementController

### ISSUE THREAD

**Issue by energinet-ajw** [Energinet-DataHub/opengeh-wholesale#1619]
Alex from Titans has verified that two endpoints in the Settlement Report Controller can be moved (they are not used in the frontend SPA).
The underlying code and tests can be removed in Wholesale, and frontend (swagger file must be updated and tests removed).

The endpoints are:
- GetAsync(...)
- GetSettlementReportAsync(...)

# Tasks
- [x] Remove GetAsync + tests from API @energinet-ajw 
- [x] Remove GetSettlementReportAsync + tests from API @energinet-ajw
- [x] PR Remove GetAsync from BFF/Frontend @energinet-ajw 
- [x] Remove GetSettlementReportAsync from BFF/Frontend?@energinet-ajw
- [x] Update Swagger doc @energinet-ajw
