### ISSUE TITLE
Quantity quality is handled according to market rules (For MDR)

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#181]
### Description
Quality is used by market actors to determine the accuracy of the results that are forwarded to them.

As datahub
i want to inform MDR role with quality of aggregated timeseries
so they can determine the accuracy of the aggregated results

### Acceptance criteria

- [ ] IF all timeseries points in the aggregated point are MEASURED
THEN quality is not shown in the RSM-014 message

```
 <cim:Point>
                <cim:position>1</cim:position>
                <cim:quantity>4.444</cim:quantity>
 </cim:Point>
```

- [ ] IF one timeseries point in the aggregated point are ESTIMATED and the rest is measured
THEN quality is set to estimated (A03) in RSM-014 message

```
 <cim:Point>
                <cim:position>1</cim:position>
                <cim:quantity>4.444</cim:quantity>
                <cim:quality>A03</cim:quality>
  </cim:Point>
```

- [ ] If one timeseries points in the aggregated point is missing quantity
THEN quality is set to incomplete (A05) in the RSM-014 message

```
 <cim:Point>
                <cim:position>1</cim:position>
                <cim:quantity>4.444</cim:quantity>
                <cim:quality>A05</cim:quality>
  </cim:Point>
```

- [ ] IF one timeseries point is ESTIMATED and another timeseries point is MISSING QUANTITY in the same aggregated point
THEN quality is set to incomplete (A05) in the RSM-014 message

```
 <cim:Point>
                <cim:position>1</cim:position>
                <cim:quantity>4.444</cim:quantity>
                <cim:quality>A05</cim:quality>
  </cim:Point>
```
