### ISSUE TITLE
Enable users to view non-profiled consumption per energy supplier in frontend

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#199]
## Description
As datahub
I want to view aggregated non-profiled consumption per energy supplier per grid area in frontend
so that a DH3 user (FAS) can support market actors in support cases and verify the results are correct based on expected output

**Non-profiled metering points:**
Metering point type = E17 
Settlement method = E02

## Acceptance criteria
- [ ] Given a balance fixing has completed, when the user (FAS user) logs in to frontend, Then aggregated quarterly timeseries for non-profiled consumption per energy supplier can be viewed
![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/0e24c842-7e0c-4ffe-b238-6ce6316ab346)

- [ ] Quarterly time series for non profiled consumption are visible in GUI per energy supplier per grid area per batch. 
- [ ] When opening the result tab then the following screenshot will show (pagination may be left out): 

![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/0cd367ac-8efe-4eda-8741-fe2dac7330b5)

## Tasks
:-)

## Done tasks
- [x] Show energy supplier list in UI @ManBearTM, @frontend-specialisten 
- [x] Handle quality correctly (handle it in __aggregate_per_ga_and_es/__aggregate_per_ga/__aggregate_per_ga_and_brp) @johevemi 
- [x] Do we risk nulling out quantity? @johevemi
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/aba338a6-3011-4be7-bcd5-0f49980c64ea)
- [x] Show result in UI @ManBearTM, @frontend-specialisten 
- [x] Get ActorList for TimeSeriesType and BatchId @lasrinnil 
- [x] why do we need to do an extra agg sum in production calc? @JesperGomes 
- [x] Unit tests in ProcessStepResultWriter @JesperGomes 
- [x] "All" .NET code regarding "step result" needs tidying up (ask Bjarke) @BjarkeMeier 
- [x] Get Consumption for a GLN @johevemi 
- [x] What is gln=__HIVE_PARITION__DEFAULT? (HIVE_DEFAULT_PARTITION will be set if a row in a column you are doing partitioning on in NULL)(this will be fixed when the gold table i updated so it can container metering point that does not have any energy supplier) @johevemi 
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/3dc09762-0c50-4db4-9248-ccc9adb73d76)
- [x] There are "blank" entries in the actor list, is that acceptable?(a row in the gln column has the value NULL and will display {} when converted to json. See related task about __HIVE_DEFAULT_PARTITION__) @johevemi 
![image.png](https://images.zenhubusercontent.com/60bdfcb3effb2082025638c1/c37f0f9e-4a0e-4552-aa87-193db0fe2256)
- [x] Migrate data according to [this structure](https://energinet.sharepoint.com/:t:/r/sites/Joules/Delte%20dokumenter/Udviklere/calculation-output.txt?csf=1&web=1&e=CIc1yQ) @johevemi 
- [x] Calculate values @JesperGomes 
- [x] Generate actor list  @JesperGomes 
- [x] Investigate why quantity ísn't constant in result/grid_area=806/gln=81000000108/... @lasrinnil 
- [x] Skip concept of environment specific settings for domain tests in DH3 workflows? Should probably cf. Dan before skipping. @BjarkeMeier 
Task just awaits MD approval of [this PR](https://github.com/Energinet-DataHub/dh3-environments/pull/350)
- [x] It appears like calculations cancelled due to migrations in CD have the following problems: @johevemi 
 1. They seem successfully complete on the "search batch" page. They should be "canceled" or "awaiting restart" or something else (It is not possible to get a canceled status out in the frontend, because when the update state function is called every 20 seconds it will ask databricks what status on the current runs are and if they are canceled it will set the status of the batch to created so it will be picked up again by the submit created batches function that runs every 10 seconds)
2. When downloading you get an empty zip file. Download should be disabled (This should have been fixed by changing the order in prepare for migration step in CD, so that ProcessManager is stopped before any current runs are canceled, making it so that a run can not change status to canceled and reset to created)
3. The process manager should automatically restart the cancelled job runs (It already does this when updating status)
- [x] Make sure that we support a meteringpoint period period switch when the resolution changes @lasrinnil 
- [x] Add this test to `ProcessResultApplicationServiceTest.cs`. It'll fail on systems using '.' (dot) as thousands separator due to the sut call to `decimal.Parse(...)`. Are we sure that Spark writing Result.json will _always_ use '.' (dot) as decimal point separator? @BjarkeMeier 
```csharp
    [Fact]
    public async Task GetResultAsync_Quantity_IsRead()
    {
        // Arrange
        var sut = ProcessResultApplicationService();

        // Act
        var actual = await sut.GetResultAsync(
            new ProcessStepResultRequestDto(
                Guid.NewGuid(),
                GridAreaCode,
                ProcessStepType.AggregateProductionPerGridArea));

        // Assert
        actual.TimeSeriesPoints.First().Quantity.Should().Be(1.000m);
    }
```

**Comment by MadsBloendAndersen** [comment]
@MadsBloendAndersen refine

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier i have combined the two issues again. :) This is the final one.

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen, I've removed this AC is not testable, outdated, and it's implied by the others and thus redundant to: "Calculate aggregated non-profiled consumption per energy supplier per grid area, using a static data set."

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen, I've removed this AC as-well as it doesn't add anything new compared to AC1: "Enable FAS user to choose results for a specific energy supplier (filtering can be left out)"
