### ISSUE TITLE
Enable FAS user to choose period when starting a balance fixing process

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#277]
### Synopsis
As a FAS user 
I want to be able to choose period when starting a balance fixing process
so that i we can run processes for different periods, which enables us to test more scenarios.  
_____________
### Acceptance Criteria
- [ ] When starting a process, GUI user must be able to choose what period the process should be run for
- [ ] When choosing period X, Then time series and metering point master data are used for period X
- [ ] Given a balance fixing has completed for period X (Chosen by GUI user), When actor peeks/dequeue RSM-014, Then results contain aggregated points for period X. 

 
________________
### Tech. Notes
________________
### Task List
_________________
#### Tasks in Development
_________________
#### Tasks Completed
_________________
