### ISSUE TITLE
Enable Fas user to see an overview of calculations performed within a certain grid area and batch 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#317]
## Description 
As a fas user 
i want to get an overview of calculations performed for a specific grid area and batch
so that i can easily access any results for the grid area

## Acceptance criteria

- [x] FAS user can select grid area from list when entering a batch.
- [x] When selecting a grid area from the list, Fas user are forwarded to a results overview screen (In this case, the only result that would appear is total production).
- [ ] When unfolding the results tab, then a table containing the following data will appear

English
| Grid area code  | Grid area name | Metering point type |
| ------------- | ------------- | ------------- | 
| 806  | Mandalorian + GLN number | E18 |

Danish
| netområde kode  | Netvirksomhed | Målepunkts type |
| ------------- | ------------- | ------------- | 
| 806  | Mandalorian + GLN number | E18 |

The design should follow the mockup: 
![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/33ed0162-5d25-4218-9b15-e169ce4e2589)

note: 
need fold out component 

### Tasks:
- [x] Rename BatchGridAreaDto to GridAreaDto
- [x] Create a DTO for processes belonging to a batch with a specific grid area (DTO name: BatchGridAreaDto)
- [x] sum, min and max.  Is it calculated or measured values? ask SME
- [x] Implement get single batch in batch controller and implement in bff
- [x] Implement a call to get the ProcessStepResultDto @lasrinnil 
- [x] Populate GridAreaName when calling GetBatches to get the names from the market participant call this this.gridAreaOverviewClient.v1MarketParticipantGridAreaOverviewGet() @lasrinnil
