### ISSUE TITLE
Measure good interactions vs total interactions when starting a batch through GUI 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#319]
### Synopsis
As a team 
we want to measure execution time when starting a new batchs
so that we get an indication of performance, when adding more calculation.
_____________
### Acceptance Criteria
- [ ] A Dashboard, visible for the business, is set up that shows how performance evolves when new calculations are coupled to the balance fixing/aggregation 
- [ ] When the execution time of the batch is faster than 8 minutes then it is considered a success. 
- [ ] The dashboard shows one bar 1-100% where 100% = success all the time within the last week.    

________________
### Tech. Notes
________________
### Task List
_________________
#### Tasks in Development
_________________
#### Tasks Completed
_________________
