### ISSUE TITLE
Peek/Dequeue RSM-14 with timeseries in result section

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#32]
Synopsis
----------------
As an MDR
I want to be able to peek and dequeue a complete RSM-014 message for total production (E18)
So that we can validate the total production (E18) result

Acceptance-Criteria
----------------
- [ ] Peek ~~a valid RSM-14~~ an RSM-014 with calculated total production quantity

Tech-Notes
----------------
- [Link to valid rsm-014 here ("Notify aggregated measure data.xml")](https://energinet.sharepoint.com/sites/DH3ART-team/Delte%20dokumenter/Forms/AllItems.aspx?csf=1&web=1&e=bgcFKW&cid=c7362f94%2D647d%2D4a98%2D8c03%2D161ab2ca5240&FolderCTID=0x012000AD9D81C11C6A0A4292E72C1B9D55F89C&id=%2Fsites%2FDH3ART%2Dteam%2FDelte%20dokumenter%2FGeneral%2FCIM%2FCIM%20XSD%20%2D%20XML%2FXML%20filer%2FXML%2020220425%20%2D%20Danske%20koder%2FNotify%20aggregated%20measure%20data%2Exml&parent=%2Fsites%2FDH3ART%2Dteam%2FDelte%20dokumenter%2FGeneral%2FCIM%2FCIM%20XSD%20%2D%20XML%2FXML%20filer%2FXML%2020220425%20%2D%20Danske%20koder)
- [Link to documentation in confluent](https://energinet.atlassian.net/wiki/spaces/DHDOCS/pages/152961305/BRS-023+-+Fremsendelse+af+beregnede+energitidsserier)
- [Link to documentation in Azure devops](https://dev.azure.com/energinet/Datahub/_wiki/wikis/DataHub/4558/BRS-023-Data-properties-needed-for-calculation-engine)

Tasks
-----------------
Spark log output from 2nd of September [here](https://adb-5870161604877074.14.azuredatabricks.net/driver-logs/0902-150104-6srn73y/download/stdout?csrf=f019d056-eb6a-4520-983d-a83c111e6e89&o=5870161604877074).
____________________________________________________________________
Test Scenarios: 
- [x] Test 1
1. Run balance fixing for grid area X for period 2022-06-30T22:00:00Z to 2022-07-01T22:00:00Z
2. Check that RSM-014 is forwarded to MDR, with aggregated timeseries

- [x] Test 2
1. Create new metering point on 2022-06-28T22:00:00Z in grid area A
2. Connect newly created metering point on 2022-06-29T22:00:00Z 
3. Submit timeseries (PT1H) on the new metering point for period 2022-06-30T22:00:00Z to 2022-07-01T22:00:00Z
4. Run balance fixing for period 2022-06-30T22:00:00 to 2022-07-01T22:00:00Z and grid area A
5. Verify that timeseries from a PT1H are correctly added to aggregated quarterly values in RSM-014 message to MDR

- [x] Test 3
1. Create new metering point on 2022-06-28T22:00:00Z in grid area A
2. Connect newly created metering point 2022-06-29T22:00:00Z
3. Submit timeseries (PT15M) on the new metering point for period 2022-06-30T22:00:00Z to 2022-07-01T22:00:00Z
4. Run balance fixing for 2022-06-30T22:00:00Z to 2022-07-01T22:00:00Z for grid area A
5. Verify that timeseries from a PT15M are added correctly to the aggregated quarterly values in RSM-014 message to MDR 

- [x] Test 4 
1. Metering point is created and connected at 2022-06-30T22:00:00Z
2. Timeseries are forwarded for date 2022-06-30T22:00:00Z to 2022-07-01T22:00:00Z
3. Run balance fixing for period 2022-06-30T22:00:00Z to 2022-07-01T22:00:00Z 
4.  Verify that timeseries from the new metering point created on date X are added correctly to the aggregated quarterly values in RSM-014 message to MDR

- [x] Test 5 
1. Every time a balance fixing is run, then only ONE RSM-014 is forwarded to each grid area represented in the calculation.    

_______________________________________________________________

- [x] Fix ambigous grid area link ids (u-001)
We have reached out to Titans. It however shouldn't break 805 or 806 as a correct event has been received latest, we have decided to take no further action on the matter (status of the envs as of this writing) (u-001)
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/0941b7bc-76e0-4c55-beb2-5fe40e1e701f)
- [x] Remove bad data: We have metering points with null values for type, link id, connection state and resolution (u-001) @johevemi 
- [x] Remove bad data: Some time series points have metering point id instead of GSRN number. That could be fixed but  they also seem to have wrong trasaction id (u-001).2 @johevemi 
```
/databricks/python/lib/python3.8/site-packages/package/balance_fixing_total_production.py:255 - _get_enriched_time_series_points_df(): Time series points where time is within period
+------------------+--------------------+---------+-------+----------+--------------------+--------------------+-------------------+----+-----+---+
|        GsrnNumber|       TransactionId| Quantity|Quality|Resolution|RegistrationDateTime|          storedTime|               time|year|month|day|
+------------------+--------------------+---------+-------+----------+--------------------+--------------------+-------------------+----+-----+---+
|              null|            C1875000|    9.090|      4|         1| 2022-08-04 08:30:00|2022-08-31 13:42:...|2022-06-01 00:00:00|2022|    6|  1|
```

- [x] Verify the AC's on U / T @lasrinnil 

**Done tasks**
- [x] Fix time series data error. See [here](https://adb-5870161604877074.14.azuredatabricks.net/?o=5870161604877074#setting/sparkui/0830-150814-vuitb64j/driver-logs). - @BjarkeMeier 
Below fixed by removing unprocessed and published data in geh-timeseries. But looks like publisher no longer publishes points, and I can't see logs from the job anymore.
```
/databricks/python/lib/python3.8/site-packages/package/balance_fixing_total_production.py in _get_enriched_time_series_points_df(time_series_points, metering_point_period_df, period_start_datetime, period_end_datetime)
    245     # If we end up with more than one point for the same Meteringpoint and "time".
    246     # We only need the latest point, this is essential to handle updates of points.
--> 247     timeseries_df = timeseries_df.withColumn(
    248         "row_number", row_number().over(window)
    249     ).where(col("row_number") == 1)
...
...
...
AnalysisException: Column 'GsrnNumber' does not exist. Did you mean one of the following? [time, month, quantity, resolution, storedTime, year, day, position, quality, start_datetime, transaction_id, metering_point_id, registration_date_time];
'Project [metering_point_id#28, transaction_id#29, quantity#30, quality#31L, position#32L, resolution#33L, start_datetime#34, registration_date_time#35, storedTime#36, time#37, year#38, month#39, day#40, row_number() windowspecdefinition('GsrnNumber, time#37, 'RegistrationDateTime DESC NULLS LAST, specifiedwindowframe(RowFrame, unboundedpreceding$(), currentrow$())) AS row_number#671]
```
- [x] Update message type of stored grid area updated events from "GridAreaUpdatedIntegrationEvent" to "GridAreaUpdated" in all environments. _Or_ replay grid area updated events for grid area 805 and 806 in all environments. - @BjarkeMeier 
- [x] Test contract between output and sender [PR #266](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/266)- @BjarkeMeier 
- [x] Switch the "old" calculator out with the new one - [PR #265](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/265) @BjarkeMeier
- [x] Test that events two events on the same time adds up to one period @lasrinnil [PR #264](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/264)
- [x] Test that events and timeseries conform to "storedTime" in the calculator @seblapela
- [x] Create test(s) that ensure that the wholesale domain expects the same schema of time series points as the time series domain [PR #260](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/260) - @johevemi 
- [x] In what order should integration events be replayed to ensure correct state (or should we get historical data from metering point domain)? - @BjarkeMeier - I have booked Søndergård and Faurskov Tuesday
- [x] Use Databricks GitHub repo for notebooks to avoid loosing them, have version control and finally make them available as part of the open-source repo. Branch 32-notebooks has been created. Also remove storage key from GitHub branch 32-notebooks in opengeh-wholesale (and probably revoke it for security reasons) @ftoft 
- [x] Clean up usage/configuration of Delta lake in wholesale repo [PR #256](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/256) - @johevemi 
- [x] Do not rely on storedTime of points for sorting. Use "time when point was received by DH3" - @BjarkeMeier 
- [x] Add tests of get_result_df @lasrinnil [PR #237](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/237)
- [x] ~~Fix todos regarding "Use range join optimization"~~ - @BjarkeMeier UPDATE: Happened to be a Delta thing
- [x] Add tests of get_metering_points_df - @BjarkeMeier 
- [x] Verify OperationTimestamp on events which are stored. Use it in balance fixing (see comment(s) in code). Should we throw when receiving events missing operation time stamp? [PR #217](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/217)) @defectiveAi 
- [x] Test that pyspark enum literals and values matches those in .NET (however not requiring that all literals must be present in pyspark) [PR #238](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/238) @defectiveAi 
- [x] Perhaps I'm wrong but looks like geh-timeseries publishes originalTransactionIDReference_Series.mRID instead of mRID as transaction ID - @lasrinnil [PR#521](https://github.com/Energinet-DataHub/geh-timeseries/pull/521)
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/df635c7d-cda8-4cad-b5ac-5c68d8f51e23)
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/5ac8a8c9-a90e-492c-883c-61923087a2d6)
- [x] Update doc in timeseries and wholesale about easier debugging of test using VSCode extension "Python Test Explorer for Visual Studio Code" - @BjarkeMeier 
- [x] Refactor tests of _get_grid_areas_df [PR #232](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/232) - @johevemi 
- [x] Implement notebook in code - @BjarkeMeier and @seblapela 
- [x] Implement consumption of MarketParticipant integration events ~place in separate container~
- [x] Create a helper in python which can parse GridAreaCodes and respond with GridAreaLinkId's for a given date.
- [x] Add metering point id to metering point events - @seblapela 
- [x] Seems like we don't publish new time series points in geh-timeseries when submitting time series - @johevemi 
- [x] Der er ikke modtaget events for 805 fra metering point, så der er testet med Batman's 112 grid area. At rette 112 til 805 i postman ser ikke ud til at være nok, når man opretter målepunkter. (from Alex' status in teams) - @BjarkeMeier 
- [x] Create Notebook to calculate balancefixing results - @BjarkeMeier and @seblapela 
- [x] Calculator is currently broken: `AnalysisException: Column 'GridAreaCode' does not exist. Did you mean one of the following? [storedTime, body, day, enqueuedTime, properties, year, offset, partition, month, partitionKey, publisher, sequenceNumber, systemProperties];` - @BjarkeMeier 
- [x] Remove series related data from points published in geh-timeseries (position and start_datetime) [PR #508](https://github.com/Energinet-DataHub/geh-timeseries/pull/508). Should "resolution" be renamed? E.g. to "duration"? (NO)  - @johevemi  
- [x] Rename MeteringPointId to GsrnNumber in geh-timeseries in order to align with wholesale? (YES) [PR #511](https://github.com/Energinet-DataHub/geh-timeseries/pull/511) - @johevemi  
- [x] Doesn't seem like geh-timeseries published points correctly with registration date time having a fallback value from creation date time [PR #508](https://github.com/Energinet-DataHub/geh-timeseries/pull/508) - @johevemi
- [x] Add tests of get_enriched_timeseries_df [PR #236](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/236) - @johevemi

**Comment by PerTHenriksen** [comment]
@EnerginetJTI - could you please provide an example file of a valid RSM-014 CIM /XML for an production aggregation? (just a link to a file in Teams is fine, xml files cannot be attached in zenhub)

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen, this story will most likely only work in u-001 until team Titans have made grid areas 805 and 806 available (as integration events) in the other environments.

**Comment by MadsBloendAndersen** [comment]
Hey @BjarkeMeier - @Tm1807 is on it. As discussed with Torben, this is a blocker for our test in T001.

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier I have added the issue that titans created, about creating grid area 805 + 806 in T001, as dependency to this issue.
