### ISSUE TITLE
Enable datahub to use migrated data for calculation of total production

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#347]
### Synopsis

As DH3
We want to calculate total production per grid area with migrated data from DH2 PRE07
so that we can mitigate risks and verify that DH3 calculates correct

_____________
### Acceptance Criteria
- [ ] Team can recommend solutions on how data are transferred from landing zone to wholesale domain.  
- [ ] Team can recommend how we can use migrated data in the current calculation of total production per grid area
- [ ] Given FAS user starts batch, when calculating total production per grid area, then migrated data are used in the calculation

________________
### Tech. Notes
________________
### Task List
_________________
#### Tasks in Development
_________________
#### Tasks Completed
_________________

**Comment by BjarkeMeier** [comment]
How will work be divided by teams with the new plan? Will all work of this feature fit in a single team? How do the PM/POs plan to optimize collaboration focusing on the first deliveries?

**Comment by BjarkeMeier** [comment]
How about a less solution-oriented/technical title and more value-oriented like e.g. "Use DH2 data for calculation of total production"?

**Comment by BjarkeMeier** [comment]
What is the value of AC 1 and 2?

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier 
**A to Q1:** As of right now (2-3 weeks), team mandalorian will be the only team looking into migration. How teams should be organized around the task of migration, will be determined at a later stage. 

**A to Q2:** Done 

**A to Q3**: Not much value in AC1 with that specific formulation. The objective of AC1 was to get a recommendation from developers on how to optimize migration. For example - should migrated data flow through each domain, or should the wholesale domain just get it directly from migrated data. I think the business will have peace at mind if this was a topic of consideration. AC2 is just a mirror of this issue/spike:https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/energinet-datahub/opengeh-wholesale/346

**Comment by BjarkeMeier** [comment]
Regarding Q1: My concern is that we start a big feature in Mandalorian and do a lot of work that is much easier delegated than the work inside the wholesale domain. That is we collaborate much less efficient towards the goal than desired.

Regarding Q3: AC 3 can't be delivered without implicitly solving AC 1 and 2. Your answer sounds like you want something that involves a presentation to the business before moving on with the actual implementation? If that is the case then how about splitting into a separate feature rather than trying to determine the work breakdown from feature ACs?
