### ISSUE TITLE
Enable user to peek/dequeue RSM-014 message when no data are available for aggregation

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#348]
## Synopsis
As a datahub
I want to generate results for a period where no data is available for aggregation
so that market actors can peek and dequeue messages without problems

## Acceptance criteria
- [ ] Given a balance fixing has run for period X, When data for that period are missing, Then RSM-014 is generated with quantity = 0 and quality = A05 

- [ ] Given a balance fixing period has run for period X, When there is a gap where there is missing data, Then RSM-014 is generated with quantity = 0 and quality = A05 for the period where the gap is.

As of now each time a calculator job run is completed, a data available notification is sent to Message Hub, even though the run did not produce any result.

![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/f56a31e7-94b6-44b9-a7b1-c7c59a5e46b1)

## Scope
It is expected there always are metering points in the selected period. If not the calculation fails

## Tasks
- [x] A result is generated for a period where some points are missing (across all metering points for a given position) - @lasrinnil 
- [x] Connected and disconnected metering points without time series in period are included in basis data
- [x] A result is generated for a period where there are no time series. 
- [x] Point values in basis data are empty (not zero)
- [x] A result is generated for a period with no time series for any metering point 
- [x] If no time series are found in the requested period a result is still generated with 0.00 and A05
- [x] Rename enums which names are used for both mp and ts domain
- [x] When a calculator job is run for a period with no metering points the job fails

**Comment by lasrinnil** [comment]
Story is ready for testing.

**Comment by MadsBloendAndersen** [comment]
Tested on T
The following data were used: 
571401444449922408 - E18 - oprettet 14. juni 2022 - tilsuttet d. 16. juni 2022 - tidsserier d. 18 juli 2022 - tidsserier d. 20 juli 2022
575491333668003580 - E18 - oprettet 14. juni 2022 - tilsuttet d. 16. juni 2022 - tidsserier d. 18 juli 2022 - tidsserier d. 20 juli 2022
574826620099133050 - E18 - oprettet 14. juni 2022 - tilsuttet d. 16. juni 2022 - tiddserier d. 18 juli 2022 - tidsserier d. 20 juli 2022
