### ISSUE TITLE
Add new "settlement report" page to wholesale 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#356]
## Description
As a energinet user
i want a new settlement report page  
so that i can see a what settlement reports i can download when a batch has finished

## Acceptance criteria
- [x] A new menu is available under "Settlement" called "Settlement reports" (English) "Afregningsrapporter" (Danish)
![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/8b26fd1c-d2c3-4715-bcfc-746998da801e)

- [x] When entering the menu "Settlement reports" then the following information is shown: 
![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/d8902b96-efbd-4638-bc43-c5223ac339eb)

- [ ] The filters used in other part of DH3 frontend can be used in this page as well

Notes: 
Only balance fixing is available as process type right now

LRN notes:
Man skal kunne søge batches med følgende udvidelser:
Afgrænsning på Periode (Til og Fra)
ExecutionState (man må kun i dette tilfælde se "Completed" batches")

Batch respons skal udvides med at vise hvilken processtype det er.

## Q&A
Q: Hvordan virker "Netområder" knappen? Er der valgt noget i den når man kommer ind på siden? A: _Netområde knappen skal kunne filtrerer i net områder i den totale liste. Der skal ikke være filtrering på netområder fra start_

Q: Hvad vises i listen når man kommer derind og endnu ikke har valgt noget selv endnu? A: Der skal vises de beregninger som har eksekverings tid indenfor den sidste måned.

Q: Ift. periode afgrænsningen, skal en given rapport ligge inde for perioden i sin helhed (rapport har start og end date liggende inde for den valgte periodeafgrænsningen), eller er det nok, at den bare rammer ind i afgrænsningen? A: Det er nok at den bare rammer ind i afgrænsningen. 

## Tasks: 
Mandalorian:
- [x] Add settlement reports page
- [x] Add filters 
- [x] Fetch / map data

Titans:
- [x] Extend API with ExecutionState + tests.
- [x] Extend API with grid areas + tests.
- ~Move API to v3 controller model.~

**Comment by MadsBloendAndersen** [comment]
@ManBearTM The period filter is still disabled. I cant use it: 

![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/e7f4172b-d81f-48b5-bc95-d51f9b44224a)
