### ISSUE TITLE
"user" can download a .zip file containing the metering point master basis data for the given period

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#502]
## Description 
As a user of datahub
I want to download master basis data based on the static data provided
So that I can verify the data is correct

## Acceptance criteria
- [ ] user can download the master basis data in a zip file from the GUI

## Task list
- [x] Provide the team with .csv file of the master basis data for the metering points and the grid areas
~~- [ ] Embed the metering point and market roles .csv's in the package @BjarkeMeier~~
- [x] Initial cleanup after transitioning from events to static data source @BjarkeMeier 
- [x] Come up with a concept for joining periods of metering points and market roles @lasrinnil @BjarkeMeier 
- [x] Cover the static metering point with sufficient test coverage @seblapela 

[https://app.zenhub.com/files/490590917/20acba70-df31-461c-a1a6-6f899f5ada78/download](https://app.zenhub.com/files/490590917/20acba70-df31-461c-a1a6-6f899f5ada78/download)
