### ISSUE TITLE
"user" can download a .zip file containing the PT1H/PT15M timeseries basis data for the given period

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#503]
## Description 
As a user of datahub
I want to download  PT1H/PT15M timeseries basis data based on the static data provided
So that I can verify the data is correct

## Acceptance criteria
- [ ] user can download the  PT1H/PT15M timeseries basis data in a zip file from the GUI

## Task list
- [x] Provide the team with a .csv file of the master basis data for the metering points and the grid areas
- [x] Refactor time series to come from the static source provided @seblapela @lasrinnil 
- [x] Remove old enums
- [ ] Investigate "Ambiguous ref" when joining frames in production errors (reproducible in tests?)

**Comment by MadsBloendAndersen** [comment]
![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/417bf5f3-c045-4420-b578-9ffb8656fe93)

**Comment by MadsBloendAndersen** [comment]
Summer winter time in result file:

![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/0b0e8dc1-5622-466c-8e74-ddf1efeeefa4)


Position 9-12 should be deleted..
