### ISSUE TITLE
[Tech] Make it possible to do automated migrations in the data lake when deploying

### ISSUE THREAD

**Issue by JesperGomes** [Energinet-DataHub/opengeh-wholesale#508]
### Synopsis
As a developer 
I want to be able to perform automated data migration in the data lake across environments
so that I have the possibilty to re-structure data when in production

_____________
### Acceptance Criteria
- [x] Uncommitted migrations are applied when deploying
- [x] all running jobs are stopped before migrations
- [x] all stopped jobs are restarted after the migrations
- [x] all data from 'processes' and 'integration-events' containers are moved to the new 'wholesale' container, and the two old containers are deleted
________________
### Tech. Notes

Pseudo algorithm for applying migrations in CD:
```Før CD: alle processer kører

- has_migrations = ...
- if has_migrations
	lock storage
	stop db jobs
	stop process manager

- overwrite wheel
- terraform

- if has_migrations
	- lake migrations
	- remove lock
	- start db jobs

- deploy process manager (implicitly starts it too)

- if has_migrations
	- ensure process manager is running: must be after deploy of new .NET code

Efter CD: alle processer kører
```

# Tasks
- [x] create Databricks migrations job - @BjarkeMeier 
- [x] add wheel entry unit tests - @BjarkeMeier 
- [x] add start/stop databricks streaming jobs: skal spille sammen med resten af CD - @seblapela 
- [x] manage migration scripts - @JesperGomes 
- [x] prevent databricks jobs from starting when storage is locked - @BjarkeMeier 
- [x] add migrations to CD pipeline - @BjarkeMeier and @lasrinnil 
  * add CD step to check if there are uncommitted migrations - awaiting MightyDucks
  * update CD to apply migrations. See tech notes
- [x] add health check for wholesale container in almost all apps - @BjarkeMeier 
- [x] make the migrations job a blocking call in the CD  - @BjarkeMeier 
- [x] use databricks cli to start and stop jobs in the CD (remeber to clean up the code in the wheel) - @BjarkeMeier 
- [x] make sure calculations are restarted if stopped due to migrations - @BjarkeMeier 
- [x] add migration script that moves data to new container - @JesperGomes 
- [x] the two old containers are deleted
