### ISSUE TITLE
[Mandalorian] Enable wholesale to use static data as input to calculations instead of events

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#509]
### Synopsis

As a team
we want to make ourselves independent from migration
so that we can continue to work on calculations
_____________
### Acceptance Criteria
- [ ] We have implemented a static that contains information regarding 
- metering points, 
- market roles, 
- timeseries, 

- [ ] We are able to run our current calculation on static data 
- [ ] DH3 user are able to download basis data and get basis data for timeseries and metering point master data 
 
________________
### Tech. Notes
________________
### Task List
_________________
#### Tasks in Development
_________________
#### Tasks Completed
_________________
