### ISSUE TITLE
Create balance fixing contracts between migration and wholesale

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#543]
### Synopsis
As a team
We want the contracts between the migration and wholesale domains for balance fixing related data in place
So that team Volt is enabled to work on delivering the desired data

### Acceptance criteria
- [x] Contracts are accepted by team Volt
- [x] Business documentation of contracts is in place
- [x] Technical documentation of contracts is in place
- [x] Contracts are reviewed by Halfspace?

### Tasks
- [x] Create contracts - @BjarkeMeier 
- [x] Settle with team Volt - @BjarkeMeier 
- [x] Settle with architects - @BjarkeMeier 
- [x] Settle with team Titans - @BjarkeMeier 
- [x] Get Halfspace input/feedback - @BjarkeMeier 
- [x] Verify whether EDI requirements are likely to be supported given the defined contracts - @BjarkeMeier 
- [x] Create business documentation - @BjarkeMeier 
- [x] Create tech documentation - @BjarkeMeier

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen , does this story include all know contracts? Or do we want to split into e.g. (1) those needed for current functionality, (2) the rest needed for balance fixing, and (3) the remaining needed for settlement?

**Comment by BjarkeMeier** [comment]
For the tester:
- business doc: https://energinet.atlassian.net/wiki/spaces/D3/pages/146505756/Afregning
- tech doc: https://github.com/Energinet-DataHub/opengeh-wholesale/tree/main/docs/inter-domain-integration
