### ISSUE TITLE
Enable energinet user to download settlement report for a specific grid access provider 

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#584]
### Synopsis
As a energinet user 
i want to download a settlement report with basis data for a grid access provider
so that i can help actors in support cases

### Acceptance criteria
- [x] Energinet user are now able to download settlement reports for a specific grid access provider from the settlement report screen
- [x] A download icon is added to the screen: 
![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/c1c88401-e2e5-41c6-ad74-5ec3f25eef48) 

- [ ] The settlement report contains the following data per grid access provider
```
1. MeteringPointMasterdata 
2. TimeseriesPT1H
3. TimeserierPT15M 
```
### Q&A
Q: Hvad skal filen hedde? A: Result_<GridAreaCode>_<GLN>-<MarketRole>_<PeriodStart>-<PeriodEnd>_<ProcesType>

Q: Hvilken periode gælder basis data for? A: Den periode fra og til der står på batchen

### Tasks

- [ ] Make no-op API for downloading a settlement report + review.
- [ ] Implement streaming of zipped settlement report in backend.
