### ISSUE TITLE
Use PRE07 data for batches

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#625]
## Description 
As a user of datahub
I want to download metering point master data and timeseries basis data based on PRE07 migration data
and to see the result of the calculation in the downloaded file and in UI
So that I can verify the connection from DH2 to DH3

## Depends On
- https://github.com/Energinet-DataHub/opengeh-migration/issues/92
- https://app.zenhub.com/workspaces/team-volt-60a61059028fd7000e49956e/issues/gh/energinet-datahub/opengeh-migration/1

UPDATE
~~Volt delivers first (ready as of 20th of December) production metering point type data for November 2020 and January 2021 for grid areas 512, 533, 543, 584. See more details in team Volts story mentioned above.~~
29th of January 2020 only - and only part of DH2 data has been migrated.

## Acceptance criteria
- [x] user can download the master data basis data in a zip file from the GUI
- [x] user can download the PT1H/PT15M timeseries basis data in a zip file from the GUI
- [x] DH3 user can view results in front end and basis data JSON file 
- [x] Delta table schemas and business doc is updated

## Tasks
- [x] Remove bad not needed positions in result.json - @BjarkeMeier 
- [x] Fix that there are multiple quantities per quarter in result - @BjarkeMeier 
- [x] Test functionality using notebook - @BjarkeMeier
   Current work is in u-001 shared notebook `pre-07-poc`
- [x] Remove obsole snapshot stuff (look for e.g. snapshot id and batch snapshot  datetime) - @lasrinnil 
- [x] Update tests to use Delta instead of CSV (by writing the CSV to Delta in test setup) - @seblapela
- [x] Remove connection state stuff - @lasrinnil 
- [x] Update docker file to use right spark, delta and jupyter version as used in databricks 
- [x] Update contract schemas and business doc @BjarkeMeier 
- [x] Rename "EffectiveDate" and "toEffectiveDate" columns back to "ToDate" and "FromDate" - @BjarkeMeier 
- [x] Delete events folders in wholesale container (manually or using a migration?)
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/b907f174-31f4-4e0d-8bb7-ffd9416af04d) - @BjarkeMeier 
- [x] Clean up this hack in `balance_fixing.py` @lasrinnil 
```python
        .withColumn(
            Colname.balance_responsible_id,
            lit("1"),  # this is not the corect value, so this need to be changed
        )
        .withColumn(
            Colname.energy_supplier_id,
            lit("1"),  # this is not the corect value, so this need to be changed
        )
    )
    metadata_fake = Metadata("1", "1", "1", "1", "1")
```

## Tech Notes
Code snippets to verify that production data exists in calculation input v2 for grid area 543 in January 2020:
```
period_start = get_date("2019-12-31T23:00Z")
period_end = get_date("2020-02-01T23:00Z")

data = (
    ts_df.join(mp_df, (ts_df["MeteringPointId"] == mp_df["MeteringPointId"]) & (ts_df["ObservationTime"] >= mp_df["FromDate"]) & ((ts_df["ObservationTime"] < mp_df["ToDate"]) | mp_df["ToDate"].isNull()), "inner")
    .where(col("GridAreaCode") == "543")
    .where((col("ObservationTime") >= period_start) & (col("ObservationTime") < period_end))
    .where(col("Type") == "E18")
    .where(col("Quantity") > 0)
 
```
