### ISSUE TITLE
ADR-102 Folder structure

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#637]
The architect wants the team to adhere to [ADR-102](https://energinet.atlassian.net/wiki/spaces/D3/pages/290390042/ADR+102+-+Folderstruktur).

## Tasks

- [x] Move source/notebooks to source/databricks/experimental-notebooks @BjarkeMeier 
- [x] From source/databricks/ move package and tests to source/databricks/calculation-engine @BjarkeMeier 
- [x] Move integration event types/contracts to infrastructure project @BjarkeMeier

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen this is requested by @Sondergaard . I told him that I don't expect us to work on this issue before completing V8 and switching to pre07 data. But it's up to you to prioritize.

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier i have coupled this issue to this feature. https://app.zenhub.com/workspaces/mandalorian-5fd22a1a59e4740018f5ab5a/issues/gh/energinet-datahub/opengeh-wholesale/202

**Comment by MadsBloendAndersen** [comment]
Estimate between 3-13. What is the exact criteria for this issue?

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier do we know more of what this issue is about?

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen , I've discussed this with @energinet-ajw and @JesperGomes . They are satisfied with the implementation. I recommend that you simply close the story.
