### ISSUE TITLE
Provide calculations results to EDI domain (non-profiled consumption)

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#750]
### Synopsis 
as EDI domain 
we want to receive calculation results for non-profiled consumption  
so that we can forward the result to energy suppliers

### Acceptance criteria 
- [ ] Calculation results for non-profiled consumption are forwarded to EDI domain. 
- [ ] Batman has accepted the solution

### Tasks - moved to #782
- [ ] Team Batman asks if we are returning wrong metering point type (production when consumption is expected)
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/20526489-ca38-438b-b429-6501c9bad36a)
- [ ] Team Batman asks if we should use "wholesale" language for quality rather than CIM language (A04 etc)?
- [ ] Add tests of web API and corresponding NuGet package @BjarkeMeier 
- [ ] Solve problem regarding publish of batch-completed-events + state update, but without distributed transaction
- [ ] Refactor API to a well defined design (resources, uri's, HTTP methods)
- [ ] Publish swagger/open-API-spec?
- [ ] Use published open API spec to generate EDI and BFF clients and stop maintaining a NuGet client package
- [ ] (Unit)test that open API spec can always be created
- [ ] Define retention policy for old API versions?
- [ ] Make sure that directory paths are tested sufficiently. f.eks. results -> calculation-output

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier is this delivered in #199?
