### ISSUE TITLE
Create basis data for a specific energy supplier within a certain grid area

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#849]
### Synopsis

As an energy supplier
I want basis data per grid area per batch (to be created)
So that I can eventually get/verify the data

### Acceptance Criteria

- [ ] Basis data is created for each energy supplier for each grid area in a batch (anticipated testing: developer provides the files to PO/SME)

#### Tasks Completed

- [x] Move basis data contract tests from test_calculator_job to test_basis_data_writer @JesperGomes 
- [x] Refactor basis data create/write code design + introduce CsvColname class @BjarkeMeier 
- [x] Create basis data for energy suppliers @BjarkeMeier 
- [x] Update existing code according to newly defined structure @energinet-ajw @BjarkeMeier 
- [x] Define folder structure for basis data files in Data Lake @energinet-ajw @BjarkeMeier 
See new folder structure in tech notes

### Tech. Notes

```<wholesale-container>
   calculation-output
      batch_id=
         basis_data
            time_series_quarter
               grouping=total_ga
                  grid_area={partitioned}
                     part-xx.csv

               grouping=es_ga
                     grid_area={partitioned}
                        energy_supplier_gln={partitioned}
                           part-xx.csv

            time_series_hour
               grouping=total_ga
                  grid_area={partitioned}
                     part-xx.csv

               grouping=es_ga
                     grid_area={partitioned}
                        energy_supplier_gln={partitioned}
                           part-xx.csv

            master_basis_data
               grouping=total_ga
                  grid_area={partitioned}
                     part-xx.csv

               grouping=es_ga
                     grid_area={partitioned}
                        energy_supplier_gln={partitioned}
                           part-xx.csv
```

**Comment by BjarkeMeier** [comment]
@MadsBloendAndersen , @khatozen what are the expected columns in the basis data files as compared to the ones we create for the energinet user per grid area?
