### ISSUE TITLE
Enable Energinet user to select both balance fixing and aggregation as process type.

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#855]
### Synopsis
As an Energinet user
I want the option to choose "Aggregation" as the process type when starting a new batch
so that I can let the market actor know what process has been completed

### Acceptance criteria 
- [x] Add the option to choose process type in the "start batch" screen (Marked with a circle)
![image.png](https://images.zenhubusercontent.com/60d0699cbe9e2f6f18493e89/50faaf89-e855-49da-b9fb-c8814f10ecc6)
- [x] When choosing process type, the following options must be available (1) Balance fixing and (2) Aggregation
- [x] When a batch is completed we will make process type available for EDI domain. 
- [x] Process type is added as a column in search batch screen. 

### Task
- [x] Find out and plan intro to frontend app
- [x] Setup AJWs PC to run frontend app
- [x] Implement feature in frontend app
- [x] Implement feature in backend
- [x] CLA
- [x] Review
- [x] Deployment - API
- [x] Deployment - Web

**Comment by MadsBloendAndersen** [comment]
@BjarkeMeier @energinet-ajw Will you take a look at this issue and comment if it needs to be revised?
