### ISSUE TITLE
Publish CalulationResultCompleted integrationevent

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#886]
### Synopsis
_____________
A lot simpler solution for the EDI domain is that Wholesale informs when a calculation result is generated in a message containing the result.
### Acceptance Criteria
________________
- [x] CalculationResultCompleted event is published to the shared integration event service bus namespace. 

### Tech. Notes
________________
### Task List
- [x] Publish result for production for TotalGA
- [x] Publish result for consumption for ES_GA
- [x] Publish result for consumption for BRP_GA
- [x] Publish result for consumption for BRP_GA containing the ES_BRP_GA

After EDI consumes the new event.
- [x] Remove [AllowAnonymous] attributes
- [x] Remove ADR-107 story (#729 / ~~#865~~)
- [x] Remove ProcessCompleted integration event distribution

- [x] Investigate why there a empty an empty entry in the actorlist

Story created from this task from #782
- [x] Publish `CalculationResultCompleted` integration events instead of "ProcessCompleted". Beware of potentially high memory usage depending on the selected code design @lasrinnil
_________________
#### Tasks in Development
_________________
#### Tasks Completed
_________________

**Comment by lasrinnil** [comment]
I have verified that the events are sent to he EDI domain with @kft
