### ISSUE TITLE
Use 'Outbox 'pattern when publishing integrationevents

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#887]
### Synopsis
_____________
To make sure we always send messages once (at least). Team Mandalorian has decided to introduce an outbox pattern when publishing integration events.

### Acceptance Criteria
________________
- [x] Use outbox pattern

### Tech. Notes
Created from this task on #782
- [x] Use outbox pattern @BjarkeMeier 
________________
### Task List

- [x] What kind of message to save to outbox message table (the whole batch result, per grid?, other)
- [x] Make new database table
- [x] Implement outbox message ingoing
- [x] Implement event dispatcher/publisher
- [x] Update event diagram (on GitHub) @energinet-ajw 
- [x] Add timer trigged clean-up function
- [x] Add timer trigged event dispatcher
- [x] Make test of PublishIntegrationEventsEndpoint @lasrinnil s
- [x] Make test of IntegrationEventTypeMapper
- [x] Make test of OutboxMessageRepository
- [x] Make test of IntegrationEventDispatcher 

- [x] Subject = messageType, // TODO: Is this needed? @lasrinnil 
- [x] I'm uncertain about this one, but an idea: Could we remove collection and thus have these tests run on the same db instance as other repository tests saving time to provisioning a db more than necessary and thus making the test suite (slightly) faster? @BjarkeMeier 
- [x] Do we save data (protobuf) varbinary eller nvarchar ?
- [x] Use batch send on service bus instead of sending single message @energinet-ajw 
- [x] ~~IntegrationEventTopicServiceBusSender?~~ I say we keep it, it basically wraps a ServiceBusSender set up for the integration event topic, this way you are sure you are using the correct sender when sending messages inter-domain or as an integration event. @lasrinnil -- I (@BjarkeMeier agree/accept - box checked)
- [x] Cancellation token?
- [x] Should we have a `CalculationResultCompletedDto` at the application layer? Is it ok to only represent the event using `byte[]`? @BjarkeMeier 
- [x] Document what the bool tells @energinet-ajw 
![image.png](https://images.zenhubusercontent.com/60c2e712ae37899de9483e3a/63d84429-3758-4ba4-8a71-ac2c46367628)
- [x] Do not commit in infrastructure in IntegrationEventInfrastructureService.cs @energinet-ajw 
- [x] The GitHub annotation on [this PR](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/965/files) shows that a lot of the outbox pattern implementation is lacking (unit) tests @energinet-ajw 
- [x] Tell others about Outbox @energinet-ajw (this will happen when we integrate with MediatR)
_______
#### Tasks in Development
_________________
#### Tasks Completed
_________________
