### ISSUE TITLE
Use published open API spec to generate BFF client in the BFF

### ISSUE THREAD

**Issue by lasrinnil** [Energinet-DataHub/opengeh-wholesale#888]
### Synopsis
_____________
To have a simpler use and less code to maintain, we are switching from creating a NuGet package and using that in the BFF - to simply using Nswag to generate the Client from our OpenAPI specs.

### Acceptance Criteria
________________
- [x] The BFF can communicate with the Wholesale API without using the Nuget package.

### Tech. Notes
________________
### Task List
_________________
- [x] Transition all enums to string representation (instead of ints)[issue](https://github.com/Energinet-DataHub/opengeh-wholesale/pull/898)
- [x] Use published open API spec for V3 to generate wholesale clients in the BFF instead of package
- [x] Add domain name to dtos and type in BFF
- [x] Move 1 ms before midnight hack to BFF on CreateBatch
- [x] Move every API call used by the BFF to v3 API in wholesale @johevemi 
- [x] Get nswag to work with stream settlementreport or make a separate client for stream
- [x] Move GetZippedBasisDataStreamAsync to V3. Do we even need this?
- [x] Remove the wholesale client package when EDI and BFF no-longer uses it
- [x] Quality in all .NET models should be enum and not string
- [x] minExecutionTime bug? (the error is in the save to repo)
- [x] update documentation in BFF?
- [x] update documentation in Wholesale?

#### Tasks in Development
_________________
#### Tasks Completed
_________________
