### ISSUE TITLE
[Mandalorian] [Enabler] UX til afregnings rapporter V2

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#917]
### Synopsis
Vi skal have fundet et nyt design på hvordan aktørene kan downloade basis data og resultater

### Acceptance criteria
- [ ] Basis data bliver altid downloaded per måned
- [ ] Resultater skal kunne downloades for en vilkårlig periode
- [ ] Man skal kunne finde basis data til nogle specifikke resultater
