### ISSUE TITLE
[Mandalorian] Balance fiksering må ikke køre for samme periode, medmindre godkendt af afregnings admin (UX + frontend + backend)

### ISSUE THREAD

**Issue by MadsBloendAndersen** [Energinet-DataHub/opengeh-wholesale#931]
### Synopsis
Som afregnings admin vil jeg være sikker på at jeg ikke kan køre en balance fiksering for samme periode, så jeg er sikker på jeg kører de rigtig processer for den rigtige periode
_____________
### Acceptance Criteria
- [ ] Givet jeg kører en balance fiksering første gang for en periode, når jeg trykker på start knappen, så bliver batchet startet
- [ ] Givet jeg kører en balance fiksering anden (eller flere) gang for den samme periode, når jeg trykker på start knappen så får jeg en pop up der fortæller mig at balance fiksering allerede er kørt for denne periode, og spørger mig og jeg alligevel gerne vil køre processen. 
- [ ] Hvis jeg trykker "ja, jeg vil gerne køre processen igen" så kommer der endnu en dialog boks op, som spørger "Er du sikker?" - og hvis jeg trykker ja, så starter batchen. 
________________
### Tech. Notes
________________
### Task List
_________________
#### Tasks in Development
_________________
#### Tasks Completed
_________________
