### ISSUE TITLE
[Tech] Lazy load all configuration in app service start

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#934]
### Synopsis
_____________
By using the option pattern (https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-7.0) various options (settings) are deferred loaded. This means that logging will be enabled when the various options are used  - nice when debugging. It also means that only needed options are retrieved.  

From MS website:

Encapsulation:
- Classes that depend on configuration settings depend only on the configuration settings that they use.
Separation of Concerns:
- Settings for different parts of the app aren't dependent or coupled to one another.

The pattern was presented at arch guild mid Marts.

### Acceptance Criteria
________________
The option pattern is used in the Wholesale Web API . The Process Manager solution is expected to change.

Create deferred loaded for; 
- [x] Databricks options
- [x] Connection strings 
- [x] DataLakeFileSystemClient (wait for Jespers solution)
- [x] AddBlobStorageContainerCheck.
- [x] AddAzureServiceBusTopic.
- [x] DateTimeZone. 

Extra
- [x] Add missing health test for Databricks (WebApi) - moved to another issue.
- [x] Rename Web API IServiceCollection from service to serviceCollection (so it matches the named used in the Process Manager).
 
### Tech. Notes
________________

### Task List
____
#### Tasks in Development
_________________
#### Tasks Completed
_________________
