### ISSUE TITLE
[Tech] Reduce complexity and improve maintenance 

### ISSUE THREAD

**Issue by energinet-ajw** [Energinet-DataHub/opengeh-wholesale#972]
### Synopsis
_____________
Our Wholesale API stack is slowly getting more complex and harder to maintain. Mediatr is a commonly used tool to simplify and reduce coupling in software. Team Mandalorian (mostly backend) has decided to introduce the tool. The tool is also used by team Batman.

The reason for introducing Mediatr is because the Outbox pattern made the code more complex (or messy) to work effective with. 

### Acceptance Criteria
________________
- [x] Code is reduced in complexity and its maintainability is improved.

The above AC has been agreed to imply the following (@lasrinil and @BjarkeMeier)
- [x] Existing stack has been refactored into modules
- [x] Modules communicate only by interface projects
- [x] Domain events have been removed (remember infra)
~~- [ ] DI registration has been moved to the modules~~
- [x] Process manager has been removed (remember infra)
- [x] Documentation has been updated/added
At least a diagram showing/explaining modules has been added.
Transaction control is documented.
- [x] Coding standard of each module is satisfactory
- [x] Application services are split into use cases in handlers
________________
### Task List
- [x] Arch. diagram is updated
  - Finalize the "Modules" diagram and move it to the GitHub @johevemi 
  _______
#### Tasks Completed
_________________
  - [x] Consider as a team if the "worker" and "handler" should have a diagram and a corresponding explanation. @BjarkeMeier 
- [ ] Consider as a team if other diagrams would make sense to GitHub from [this miroboard](https://miro.com/app/board/uXjVODthRHw=/?invite_link_id=155930882924) @BjarkeMeier UPDATE: Decided not to 
- [x] Move existing doc from repo to Confluence @BjarkeMeier 
- [x] Fix CD regarding locking of storage while migrating delta data @BjarkeMeier 
  - @lasrinnil have asked Svend about this - he said it would fail the write - bases on this link https://docs.databricks.com/optimizations/isolation-level.html
- [x] Clean up folder/file structure and class names in batch module @lasrinnil @johevemi 
- [x] Add test of the workers (IHostedService instances) @BjarkeMeier 
  - Add error handling in RepeatingWorker to avoid worker problems tearing down the host?
~~- [ ] UoW in a shared location?~~
- [x] Split BatchApplicationService into handler use cases @johevemi 
- [x] Would a single ProcessType make things ALOT easier? @BjarkeMeier 
- [x] Fix project relations/references @BjarkeMeier 
- [x] Clean up shared configuration in web API
- [x] Make the workers (IHostedService) DRY (share common functionality) @BjarkeMeier 
- [x] Remove db migrations deleting old batches as it is dangerous to keep in the future @BjarkeMeier 
- [x] Add CreationDateTime to db table Batch @BjarkeMeier 
- [x] Replace boolean IsPublished in db table CompletedBatch with DATETIME2 PublishedDateTime @BjarkeMeier 
- [x] each module contains a way to register itself @BjarkeMeier 
- [x] Remove process manager @johevemi 
- [x] Add tests for PR #1143 @BjarkeMeier 
- [x] Remove all domain event related code @BjarkeMeier 
- [x] Remove dh3infra related to domain events @BjarkeMeier 
- [x] branch 1083 -> remove our own wrapper of the DataBricksClient @johevemi
