### ISSUE TITLE
[Security] Protect data from being accessed by non-authorized parties

### ISSUE THREAD

**Issue by BjarkeMeier** [Energinet-DataHub/opengeh-wholesale#979]
### Synopsis
As a system owner
I want data to be protected from un-authorized access
So that I don't end up on the front page of EkstraBladet

### Acceptance Criteria
- [x] Authorization of wholesale API is protected according to ADR-105

### Task List
- [x] Talk to Titans regarding auth setup and tests
- [x] Test: Implement that all controllers/methods have the Authorize attribute
- [x] Test: Implement that all controllers/methods have the correct roles in the Authorize attribute
- [x] NOT POSSIBLE. Test: Implement that Web API security works on a single real endpoint
- [x] Add permissions to Market Participant solution (talk to Mads before that)
- [x] Review with developers
- [x] Ensure that Swagger still works with token
- [x] The frontend menu items Afregningsrapporter and Afregning are only visible with the right permissions
